version: '3'

tasks:

  generate:
    desc: Generate Terraform files
    cmds:
      - |
         tfplugingen-openapi generate \
          --config ./generator_config.yml \
          --output ./provider_code_spec.json \
          ./openapi_spec.yaml
      - |
         tfplugingen-framework generate all \
          --input provider_code_spec.json \
          --output internal/provider --package provider
    silent: false
  scaffold-datasource:
    desc: create a skaffoled datasource which can edited afterwards
    cmds:
      - tfplugingen-framework scaffold data-source --name transaction_checks --output-dir ./internal/provider